services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    entrypoint: redis-server 
    restart: always
  app:
    container_name: redigo
    image: golang:1.25
    volumes:
      - ./app:/app
    command: go run . 
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    env_file:
        - .env
    
